# Generated by Django 5.1.7 on 2025-06-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_google_user",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
