# Generated by Django 5.1.7 on 2025-04-11 12:13

import detection.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=detection.models.detection_image_upload_path,
                    ),
                ),
                ("timestamp", models.BigIntegerField()),
                ("detection_date", models.BigIntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BoundingBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                ("x2", models.FloatField()),
                ("y2", models.FloatField()),
                ("cx", models.FloatField()),
                ("cy", models.FloatField()),
                ("w", models.FloatField()),
                ("h", models.FloatField()),
                ("cnf", models.FloatField()),
                ("cls", models.IntegerField()),
                ("cls_name", models.CharField(max_length=100)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bounding_boxes",
                        to="detection.detectionresult",
                    ),
                ),
            ],
        ),
    ]
