# Generated by Django 5.1.7 on 2025-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
