# Generated by Django 5.1.7 on 2025-04-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_detectionresult_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
