# Generated by Django 5.1.7 on 2025-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_alter_detectionresult_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="updated_at1",
            field=models.BigIntegerField(null=True),
        ),
    ]
