# Generated by Django 5.1.7 on 2025-06-20 11:55

import cloudinary_storage.storage
import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0004_detectionresult_updated_at1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=detection.models.detection_image_upload_path,
            ),
        ),
    ]
